import { input } from "./input.js";

const example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

const lines = input.split('\n').map(line => line.split(''))

let numberOfSplits = 0;

let activeBeam = new Set([lines[0].indexOf('S')])

for (const line of lines.slice(1)) {
  const newBeam = new Set();
  for (const index of activeBeam) {
    const encountered = line[index]
    if (encountered === '.') newBeam.add(index);
    else if (encountered === '^') {
      numberOfSplits++;
      if (index > 0) newBeam.add(index - 1);
      if (index < line.length - 1) newBeam.add(index + 1);
    }
  }
  activeBeam = newBeam
}

console.log(numberOfSplits)